# Generated by Django 3.1.4 on 2021-12-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_etebase', '0037_auto_20210127_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionitemrevision',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
